from app.controller.scraping import extrair_dados, obter_categorias
from app.controller.eiprice_db import aplicar_banco, consultar
from fastapi import FastAPI
import pandas as pd


# Cria a tabela e adiciona a categoria.
#aplicar_banco(f"CREATE TABLE categoria (id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 42 CYCLE), nome varchar, primary key (id))")
#aplicar_banco(f"INSERT INTO categoria (nome) SELECT 'alimentos' WHERE NOT EXISTS (SELECT * FROM categoria WHERE nome = 'alimentos')")


# Chama a função para realizar o scraping e armazenas no banco de dados
#extrair_dados(obter_categorias("alimentos", "*", "*"))

app = FastAPI()

@app.get("/categoria/")
async def read_categoria():
    dados_recebido = consultar(f"select id, nome from categoria")
    df = pd.DataFrame(dados_recebido, columns=['id', 'nome'])
    dd = df.set_index("id").T.to_dict("dict")
    return dd


@app.get("/categoria/{id_categoria}")
async def read_categoria_id(id_categoria: str):
    dados_recebido = consultar(f"select id, distinct(nome) from categoria where id = '{id_categoria}'")
    df = pd.DataFrame(dados_recebido, columns=['id', 'nome'])
    dd = df.set_index("id").T.to_dict("dict")
    return dd


@app.get("/categoria/departamento/")
async def read_departamento():
    dados_recebido = consultar(f"select id, nome from sub_categoria")
    df = pd.DataFrame(dados_recebido, columns=['id','nome'])
    dd = df.set_index("id").T.to_dict("dict")
    return dd

@app.get("/categoria/departamento/{id_departamento}")
async def read_departamento_id(id_departamento: str):
    dados_recebido = consultar(f"select id, nome from sub_categoria where id = '{id_departamento}'")
    df = pd.DataFrame(dados_recebido, columns=['id', 'nome'])
    dd = df.set_index("id").T.to_dict("dict")
    return dd
 

